"""
GenAI Citation for April:
These tests were generated by Cursor using Sonnet 4.5 and reviewed by me.
Since I am learning how to test Django applications, I asked Cursor to provide descriptive docstrings for each test.
The conversation transcript is located in `GenAI_transcripts/2025_11_02_CursorVaultTests.md`

Vault Test Utilities

This module provides helper functions for creating test data in vault tests.

Why these utilities exist:
    - Your custom User model requires an auth_key field
    - auth_key is derived during registration using cryptographic functions
    - Standard User.objects.create_user() doesn't generate auth_key
    - Without auth_key, JWT login fails with NoneType errors

These utilities:
    - Generate proper auth_keys like the real registration flow
    - Avoid API calls (faster tests)
    - Keep tests focused on what they're actually testing
    - Are reusable across all vault tests that need authenticated users
"""

from auth_service.models import User
from auth_service.utils import derive_vault_key, derive_auth_key


def create_user_with_auth_key(
    username: str, email: str, password: str
) -> User:
    """
    Create a test user with a properly derived auth_key.

    This function mimics what the registration endpoint does, but without
    making an API call. Use this when you need users that can authenticate
    with JWT tokens in your tests.

    Args:
        username: The username for the new user
        email: The email address (used in key derivation)
        password: The master password (used in key derivation)

    Returns:
        User: A User instance with a valid auth_key that can login

    Example:
        ```python
        def setUp(self):
            self.user = create_user_with_auth_key(
                username='testuser',
                email='test@example.com',
                password='TestPassword123'
            )
            # Now self.user can login with JWT authentication
        ```

    How it works:
        1. Derives vault_key from email + master_password (PBKDF2)
        2. Derives auth_key from vault_key + master_password (PBKDF2)
        3. Creates user with Django's create_user() method
        4. Sets the auth_key field on the user
        5. Saves the user to the database

    References:
        - auth_service.utils.derive_vault_key()
        - auth_service.utils.derive_auth_key()
        - auth_service.serializers.RegisterSerializer.create()
    """
    # Step 1: Derive cryptographic keys (same as registration)
    vault_key = derive_vault_key(email, password)
    auth_key = derive_auth_key(vault_key, password)

    # Step 2: Create the user with Django's standard method
    user = User.objects.create_user(
        username=username, email=email, password=password
    )

    # Step 3: Set the auth_key (hex-encoded) and save
    user.auth_key = auth_key.hex()
    user.save()

    return user
