"""
** GenAI Citation for April: **
Portions of this code related to Databases and Google Cloud were generated with
the help of ChatGPT-5 and Cursor with the Claude-4.5-sonnet model.
The conversation transcript [ChatGPT-5linked here](https://chatgpt.com/share/68fec1e7-10fc-8009-9bda-bdffef8ebea6)
and [Cursor linked here](../GenAI_transcripts/2025_10_26_CursorReview.md)
documents the GenAI Interaction that led to my code.
See Pull Request here: https://github.com/beckywong37/secure-password-manager/pull/6

** GenAI Citation for Becky: **
Portions of this code related to CORS settings and configurations were
generated with the help of ChatGPT-5.
The conversation transcript [ChatGPT-5 linked here](https://chatgpt.com/c/69045b2c-e3f4-832b-bd71-d59fcef093c6)
documents the GenAI Interaction that led to my code.


Django settings for password_manager project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import environ

# ** GenAI Citation for April: **
# Portions of this code related to Environment Variables were generated with
# the help of Cursor with the Claude-4.5-sonnet model
# The conversation transcript [Cursor linked here](../GenAI_transcripts/2025_10_27_Cursor_debugging_missing_local_secret_key.md)
# documents the GenAI Interaction that led to my code.
# See Pull Request here: https://github.com/beckywong37/secure-password-manager/pull/6

# Initialize environ
env = environ.Env()
# Read .env file if it exists (for local development)
env_file = os.path.join(Path(__file__).resolve().parent.parent, ".env")
if os.path.exists(env_file):
    environ.Env.read_env(env_file)


def _get_secret_or_env(name: str, default: str = "") -> str:
    """
    Try Secret Manager first (only if we have a project id and library),
    otherwise fall back to environment variables (for local dev/CI).
    """
    project_id = (
        os.environ.get("GOOGLE_CLOUD_PROJECT")
        or os.environ.get("GCP_PROJECT")
        or ""
    )
    # Quick exit if we don't have a project id (e.g., local dev)
    if not project_id:
        return os.environ.get(name, default)

    # Try Secret Manager
    try:
        from google.cloud import (
            secretmanager,
        )  # imported here so local dev can skip

        client = secretmanager.SecretManagerServiceClient()
        resource = f"projects/{project_id}/secrets/{name}/versions/latest"
        resp = client.access_secret_version(name=resource)
        return resp.payload.data.decode("utf-8")
    except Exception:
        # Fallback to local dev env if Secret Manager is unavailable
        return os.environ.get(name, default)


# --- Core settings ---
# In cloud: SECRET_KEY comes from Secret Manager
# Local/CI: falls back to env (.env for local, GH Secret for CI)
# Use env() to read from .env file (django-environ), with fallback to _get_secret_or_env
SECRET_KEY = _get_secret_or_env("SECRET_KEY", env("SECRET_KEY", default=""))

DEBUG = env("DEBUG", default="False") == "True"

# Development fallback: Only use a default SECRET_KEY in DEBUG mode
# For production, SECRET_KEY must be set via environment variable or Secret Manager
if not SECRET_KEY and DEBUG:
    SECRET_KEY = (
        "django-insecure-dev-key-change-in-production-do-not-use-in-production"
    )
    import warnings

    warnings.warn(
        "Using default SECRET_KEY for development. Set SECRET_KEY in .env or environment for production!",
        UserWarning,
    )

USE_CLOUD_SQL = os.environ.get("USE_CLOUD_SQL", "False") == "True"

RUN_POSTGRES_TESTS = os.environ.get("RUN_POSTGRES_TESTS") == "True"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ALLOWED_HOSTS = [
    ".appspot.com",
    os.environ.get("APPENGINE_URL", "").replace("https://", "").strip("/")
    or "",
]

# Add localhost only in development
if DEBUG:
    ALLOWED_HOSTS.extend(["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp.plugins.otp_totp",
    "two_factor",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "auth_service",
    "generator",
    "vault",
]

# DRF configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# DRF Simple JWT configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# drf-spectacular configuration
SPECTACULAR_SETTINGS = {
    "TITLE": "Secure Password Manager API",
    "DESCRIPTION": "API for managing secure password records and user authentication",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware must be before CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "password_manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "password_manager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# --- Database settings ---
DB_NAME = os.environ.get("DB_NAME", "postgres")
DB_USER = os.environ.get("DB_USER", "postgres")

# Pull from Secret Manager (or env fallback)
DB_PASSWORD = _get_secret_or_env("DB_PASSWORD", "")

if RUN_POSTGRES_TESTS:
    # CI: run tests against a local Postgres service container
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("PGDATABASE", "testdb"),
            "USER": os.environ.get("PGUSER", "postgres"),
            "PASSWORD": os.environ.get("PGPASSWORD", "postgres"),
            "HOST": os.environ.get("PGHOST", "127.0.0.1"),
            "PORT": os.environ.get("PGPORT", "5432"),
        }
    }

if USE_CLOUD_SQL:
    DB_NAME = os.environ.get("DB_NAME", "")
    DB_USER = os.environ.get("DB_USER", "")
    DB_PASSWORD = _get_secret_or_env(
        "DB_PASSWORD", os.environ.get("DB_PASSWORD", "")
    )

    INSTANCE_CONNECTION_NAME = os.environ.get("INSTANCE_CONNECTION_NAME", "")
    if INSTANCE_CONNECTION_NAME:
        HOST = f"/cloudsql/{INSTANCE_CONNECTION_NAME}"  # App Engine socket
        PORT = ""
    else:
        HOST = os.environ.get("DB_HOST", "127.0.0.1")  # e.g., CI with proxy
        PORT = os.environ.get("DB_PORT", "5432")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": HOST,
            "PORT": PORT,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User model for authentication from auth app
AUTH_USER_MODEL = "auth_service.User"

# Security settings for production
if not DEBUG:
    # HTTPS enforcement
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS headers
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Additional security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# CSRF trusted origins for production
APPENGINE_URL = os.environ.get("APPENGINE_URL", "")
if APPENGINE_URL:
    CSRF_TRUSTED_ORIGINS = [APPENGINE_URL.rstrip("/")]
# CORS settings for frontend-backend communication
# Allow all origins in development (DEBUG=True)
# In production, specify exact origins
CORS_ALLOW_ALL_ORIGINS = DEBUG

# If not allowing all origins, specify allowed origins
if not DEBUG:
    CORS_ALLOWED_ORIGINS = [
        APPENGINE_URL.rstrip("/") if APPENGINE_URL else "",
    ]
else:
    # In development, allow common frontend ports
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",  # Vite default port
        "http://localhost:3000",  # React default port
        "http://127.0.0.1:5173",
        "http://127.0.0.1:3000",
    ]

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allowed headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
