# Generated by Django 5.2.7 on 2025-11-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
